Write a function so that the columns of the output matrix are powers of the input
vector.
The order of the powers is determined by the increasing boolean argument. Specifically, when
increasing is False, the i-th output column is the input vector raised element-wise to the power
of N - i - 1.

HINT: Such a matrix with a geometric progression in each row is named for Alexandre-
Theophile Vandermonde.

In [1]:
#using vander()
import numpy as np
import pandas as pd
x= np.array([1,2,3,4])
n=5
np.vander(x,n)

array([[  1,   1,   1,   1,   1],
       [ 16,   8,   4,   2,   1],
       [ 81,  27,   9,   3,   1],
       [256,  64,  16,   4,   1]])

In [2]:
x=np.array([1,2,3,4])
np.vander(x,increasing=True)

array([[ 1,  1,  1,  1],
       [ 1,  2,  4,  8],
       [ 1,  3,  9, 27],
       [ 1,  4, 16, 64]])

In [3]:
#function
def vandercopy(arr,n,inc):
    if inc:
        mat=np.matrix([x**i for x in arr for i in range(n)]).reshape(arr.size,n)
    else:
        mat=np.matrix([x**(n-i-1) for x in arr for i in range(n)]).reshape(arr.size,n)
    return mat

arr=np.array([1,2,3,4])
n=4
mat=vandercopy(arr,n,inc=True)
mat

matrix([[ 1,  1,  1,  1],
        [ 1,  2,  4,  8],
        [ 1,  3,  9, 27],
        [ 1,  4, 16, 64]])

In [4]:
mat=vandercopy(arr,n,inc=False)
mat

matrix([[ 1,  1,  1,  1],
        [ 8,  4,  2,  1],
        [27,  9,  3,  1],
        [64, 16,  4,  1]])

Write a function to find moving average in an array over a window:
Test it over [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and window of 3.

In [5]:
import numpy as np
def moving_avg(x, n):
    cumsum = np.cumsum(np.insert(x, 0, 0))
    return (cumsum[n:] - cumsum[:-n]) / float(n)

n = 3
x = [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150]
moving_avg(x, n)

array([  5.        ,   4.66666667,   5.66666667,   6.66666667,
         9.66666667,  28.66666667,  49.33333333,  72.66666667,
        84.        ,  93.33333333, 116.33333333])